# Generated by Django 5.2.1 on 2025-10-01 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromocaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('desconto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('retroativa', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=False)),
                ('categorias', models.ManyToManyField(blank=True, help_text='Deixe vazio para aplicar a todos os produtos', to='produtos.categoria')),
            ],
        ),
    ]
